#ifndef GOOEY_NODE_MANAGER_ENUMS_H
#define GOOEY_NODE_MANAGER_ENUMS_H

enum EGooeyNodeManagerNetworkID {
    E_GOOEY_MANAGER_NETWORK_NONE,
    E_GOOEY_MANAGER_NETWORK_POPPET,
    E_GOOEY_MANAGER_NETWORK_COUNT
};


#endif // GOOEY_NODE_MANAGER_ENUMS_H