#ifndef ALEAR_REVISIONS_H
#define ALEAR_REVISIONS_H

enum AlearSR {
    ALEAR_INITIAL = 1,
    
    ALEAR_LATEST_PLUS_ONE
};

enum AlearBranchSR {
    ALEAR_BR1_INITIAL = 1,

    ALEAR_POPIT_STYLES,
    ALEAR_HIDDEN_CATEGORIES,
    ALEAR_EMOTES,
    ALEAR_ANIMATION_STYLES,
    ALEAR_PARAMETER_ANIMATIONS,
    ALEAR_PINS,
    ALEAR_EXPLOSIVES,

    ALEAR_BR1_LATEST_PLUS_ONE
};

#endif // ALEAR_REVISIONS_H