#pragma once

enum eAlearSR {
    ALEAR_INITIAL = 1,
    
    ALEAR_LATEST_PLUS_ONE
};

enum eAlearBranchSR {
    ALEAR_BR1_INITIAL = 1,

    ALEAR_POPIT_STYLES,
    ALEAR_HIDDEN_CATEGORIES,
    ALEAR_EMOTES,
    ALEAR_ANIMATION_STYLES,
    ALEAR_PARAMETER_ANIMATIONS,
    ALEAR_PINS,
    ALEAR_EXPLOSIVES,

    ALEAR_BR1_LATEST_PLUS_ONE
};

#define ALEAR_LATEST (ALEAR_LATEST_PLUS_ONE - 1)
#define ALEAR_BR1_LATEST (ALEAR_BR1_LATEST_PLUS_ONE - 1)
