#ifndef ALEAR_REVISIONS_H
#define ALEAR_REVISIONS_H

enum AlearSR {
    ALEAR_INITIAL = 1,
    ALEAR_POPIT_STYLES,
    ALEAR_TEST_MARKER,
    ALEAR_HIDDEN_CATEGORIES,
    ALEAR_EMOTES,
    ALEAR_COMPRESSION_FLAGS,
    ALEAR_ANIMATION_STYLES,

    ALEAR_LATEST_PLUS_ONE
};

#endif // ALEAR_REVISIONS_H