enum ELethalType {
    LETHAL_NOT,
    LETHAL_FIRE,
    LETHAL_ELECTRIC,
    LETHAL_ICE,
    LETHAL_CRUSH,
    LETHAL_SPIKE,
    LETHAL_POISON_GAS,
    LETHAL_POISON_GAS2,
    LETHAL_POISON_GAS3,
    LETHAL_POISON_GAS4,
    LETHAL_POISON_GAS5,
    LETHAL_POISON_GAS6,
    LETHAL_NO_STAND,
    LETHAL_BULLET,
    LETHAL_DROWNED,
    
    LETHAL_TYPE_COUNT
};