#ifndef INPUT_MODE_H
#define INPUT_MODE_H

enum EInputMode {
    INPUT_NONE=0,
    INPUT_SACKBOY=1,
    INPUT_POPPET=2,
    INPUT_POD_COMPUTER=4,
    INPUT_SNAPPY_SNAPS=8,
    INPUT_OVERLAY_UI=16,
    INPUT_EARTH=32,
    INPUT_POPPET_REMOTE=64,
    INPUT_POPPET_UI=128,
    INPUT_POPPET_VIDEO=256,
    INPUT_ATTRACTION_VIDEO=512,
    INPUT_POPPET_STATE=1024,
    INPUT_SAVE_AS=2048,
    INPUT_PLANETS=2080,
    INPUT_DIRECT_CONTROL=4096,
    INPUT_ALL=0x1eff
};

#endif // INPUT_MODE_H