#ifndef PART_TYPE_ENUM_H
#define PART_TYPE_ENUM_H

enum EPartType
{
    PART_TYPE_BODY=0,
    PART_TYPE_JOINT=1,
    PART_TYPE_WORLD=2,
    PART_TYPE_RENDER_MESH=3,
    PART_TYPE_POS=4,
    PART_TYPE_TRIGGER=5,
    PART_TYPE_YELLOW_HEAD=6,
    PART_TYPE_AUDIO_WORLD=7,
    PART_TYPE_ANIMATION=8,
    PART_TYPE_GENERATED_MESH=9,
    PART_TYPE_LEVEL_SETTINGS=10,
    PART_TYPE_SPRITE_LIGHT=11,
    PART_TYPE_SCRIPT_NAME=12,
    PART_TYPE_CREATURE=13,
    PART_TYPE_CHECKPOINT=14,
    PART_TYPE_STICKERS=15,
    PART_TYPE_DECORATIONS=16,
    PART_TYPE_SCRIPT=17,
    PART_TYPE_SHAPE=18,
    PART_TYPE_EFFECTOR=19,
    PART_TYPE_EMITTER=20,
    PART_TYPE_REF=21,
    PART_TYPE_META_DATA=22,
    PART_TYPE_COSTUME=23,
    PART_TYPE_CAMERA_TWEAK=24,
    PART_TYPE_SWITCH=25,
    PART_TYPE_SWITCH_KEY=26,
    PART_TYPE_GAMEPLAY_DATA=27,
    PART_TYPE_ENEMY=28,
    PART_TYPE_GROUP=29,
    PART_TYPE_PHYSICS_TWEAK=30,


    // this enum controls the size of some data structures and is the last 
    // official part supported by LBP1, so it has to stay here. 
    PART_TYPE_SIZE = 31, 
    
    PART_TYPE_NPC = 31, 
    PART_TYPE_SWITCH_INPUT, 
    PART_TYPE_MICROCHIP, 
    PART_TYPE_MATERIAL_TWEAK, 
    PART_TYPE_MATERIAL_OVERRIDE, 
    PART_TYPE_INSTRUMENT, 
    PART_TYPE_SEQUENCER, 
    PART_TYPE_CONTROLINATOR, 
    PART_TYPE_POPPET_POWERUP, 
    PART_TYPE_POCKET_ITEM, 
    PART_TYPE_TRANSITION, 
    PART_TYPE_FADER, 
    PART_TYPE_ANIMATION_TWEAK, 
    PART_TYPE_WIND_TWEAK, 
    PART_TYPE_POWERUP, 
    PART_TYPE_HUD_ELEM, 
    PART_TYPE_TAG_SYNCHRONIZER, 
    PART_TYPE_WORMHOLE, 
    PART_TYPE_QUEST, 
    PART_TYPE_CONNECTOR_HOOK, 
    PART_TYPE_ATMOSPHERIC_TWEAK, 
    PART_TYPE_STREAMING_DATA, 
    PART_TYPE_STREAMING_HINT 
};

#endif // PART_TYPE_ENUM_H