#ifndef PART_MACRO
    #define PART_MACRO(name, type) class name;
    #define PART_MACRO_EPHEMERAL
#endif

PART_MACRO(PBody, PART_TYPE_BODY)
PART_MACRO(PJoint, PART_TYPE_JOINT)
PART_MACRO(PWorld, PART_TYPE_WORLD)
PART_MACRO(PRenderMesh, PART_TYPE_RENDER_MESH)
PART_MACRO(PPos, PART_TYPE_POS)
PART_MACRO(PTrigger, PART_TYPE_TRIGGER)
PART_MACRO(PYellowHead, PART_TYPE_YELLOW_HEAD)
PART_MACRO(PAudioWorld, PART_TYPE_AUDIO_WORLD)
PART_MACRO(PAnimation, PART_TYPE_ANIMATION)
PART_MACRO(PGeneratedMesh, PART_TYPE_GENERATED_MESH)
PART_MACRO(PLevelSettings, PART_TYPE_LEVEL_SETTINGS)
PART_MACRO(PSpriteLight, PART_TYPE_SPRITE_LIGHT)
PART_MACRO(PScriptName, PART_TYPE_SCRIPT_NAME)
PART_MACRO(PCreature, PART_TYPE_CREATURE)
PART_MACRO(PCheckpoint, PART_TYPE_CHECKPOINT)
PART_MACRO(PStickers, PART_TYPE_STICKERS)
PART_MACRO(PDecorations, PART_TYPE_DECORATIONS)
PART_MACRO(PScript, PART_TYPE_SCRIPT)
PART_MACRO(PShape, PART_TYPE_SHAPE)
PART_MACRO(PEffector, PART_TYPE_EFFECTOR)
PART_MACRO(PEmitter, PART_TYPE_EMITTER)
PART_MACRO(PRef, PART_TYPE_REF)
PART_MACRO(PMetaData, PART_TYPE_META_DATA)
PART_MACRO(PCostume, PART_TYPE_COSTUME)
PART_MACRO(PCameraTweak, PART_TYPE_CAMERA_TWEAK)
PART_MACRO(PSwitch, PART_TYPE_SWITCH)
PART_MACRO(PSwitchKey, PART_TYPE_SWITCH_KEY)
PART_MACRO(PGameplayData, PART_TYPE_GAMEPLAY_DATA)
PART_MACRO(PEnemy, PART_TYPE_ENEMY)
PART_MACRO(PGroup, PART_TYPE_GROUP)
PART_MACRO(PPhysicsTweak, PART_TYPE_PHYSICS_TWEAK)

#ifdef PART_MACRO_EPHEMERAL
    #undef PART_MACRO
    #undef PART_MACRO_EPHEMERAL
#endif
