#ifndef PLAYER_NUMBER_INL
#define PLAYER_NUMBER_INL

enum EPlayerNumber
{
    E_PLAYER_NUMBER_NONE = -1,
    E_PLAYER_NUMBER_0 = 0,
    E_PLAYER_NUMBER_1,
    E_PLAYER_NUMBER_2,
    E_PLAYER_NUMBER_3,
    E_PLAYER_NUMBER_4,
    E_PLAYER_NUMBER_5,
    E_PLAYER_NUMBER_6,
    E_PLAYER_NUMBER_7,
    E_PLAYER_NUMBER_8,
    E_PLAYER_NUMBER_9,
    E_PLAYER_NUMBER_10,
};

#endif // PLAYER_NUMBER_INL