#ifndef RESOURCE_ENUMS_H
#define RESOURCE_ENUMS_H

enum EResourceLoadState
{
    LOAD_STATE_UNLOADED,
    LOAD_STATE_LOADING,
    LOAD_STATE_PENDING_DESERIALISE,
    LOAD_STATE_LOADED,
    LOAD_STATE_ERROR,
    LOAD_STATE_ERROR_BADHASH,
    LOAD_STATE_ERROR_FILENOTFOUND,
    LOAD_STATE_ERROR_FAILED_LOAD_BLURAY,
    LOAD_STATE_ERROR_FAILED_HASH_COMPARE,
    LOAD_STATE_ERROR_NO_DATA_SOURCE
};

enum ESerialisationMode
{
    MODE_SAVE,
    MODE_LOAD
};

enum ESerialisationType
{
    PREFER_BINARY,
    PREFER_TEXT,
    PREFER_FILE,
    PREFER_DEFAULT,
    PREFER_ENCRYPTED
};

enum EWaitForStreamingResources
{
    WAIT_FOR_STREAMING_RESOURCES,
    DONT_WAIT_FOR_STREAMING_RESOURCES
};

#endif // RESOURCE_ENUMS_H