#pragma once

enum EStick
{
    STICK_WALK,
    STICK_FLY,
    STICK_GRAB,
    STICK_CURSOR,
    STICK_PAINT,
    STICK_VERTEX,
    STICK_TRANSLATE,
    STICK_ROTATE,
    STICK_SCALE,
    STICK_MEDIA_BAR,
    STICK_PLAN,
    STICK_PHOTO,
    STICK_SLIDER_MENU,
    STICK_SLIDER_TWEAK,
    STICK_TWEAK_LEFT,
    STICK_BOX_2D_SCALE,
    STICK_GOOEY,
    STICK_JETPACK,
    STICK_EARTH,
    STICK_GRID_TRANSLATE_DELAY,
    STICK_GRID_SCALE_DELAY,
    STICK_TOOL,
    STICK_LOOKSMENU
};
