add_custom_command(TARGET ${PROJECT_NAME} POST_BUILD
    COMMAND ${PS3_PRX_STRIP} ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/alear.prx -o ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/alear.prx.stripped
)

add_custom_command(TARGET ${PROJECT_NAME} POST_BUILD
    COMMAND ${PS3_MAKE_FSELF} ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/alear.prx.stripped ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/alear.sprx
)