add_custom_command(TARGET ${PROJECT_NAME} POST_BUILD
    COMMAND ${MAKE_FSELF} ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/alear.prx ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/alear.sprx
)

add_custom_command(TARGET ${PROJECT_NAME} POST_BUILD
	COMMAND ${CMAKE_COMMAND} -E copy_directory
	"${CMAKE_RUNTIME_OUTPUT_DIRECTORY}"
	"E:/emu/rpcs3/dev_hdd0/game/LBP1DEBUG/USRDIR/")